# Generated by Django 4.2.7 on 2023-11-22 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 7, 31, 19, 743575, tzinfo=datetime.timezone.utc)),
        ),
    ]
